### ISSUE TITLE
[BUG] This repo is not published on npm anymore

### ISSUE THREAD

**Issue by Fonger** [npm/package-json#33]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It's not available on npm now.

https://www.npmjs.com/package/@npmcli/package-json
<img width="636" alt="image" src="https://github.com/npm/package-json/assets/5862369/b14e8338-9268-4b7b-9e2d-b59d1c8648e9">

### Steps To Reproduce

1. In this environment - N/A
2. With this config N/A
3. Run 'yarn add @npmcli/package-json' or visit https://www.npmjs.com/package/@npmcli/package-json
4. See error...

### Environment

- npm:
- Node:
- OS:
- platform:

**Comment by dhensby** [comment]
It looks like the package has now been made private on npm - also having this problem when trying to install

**Comment by aitormunoz** [comment]
Currently npm is having some problems, maybe it has something to do...
https://status.npmjs.org/

> Investigating - We are investigating increased latency in our authentication service, affecting package installation and publishing

Hopefully it gets fixed soon..

**Comment by Fonger** [comment]
For those who are blocked due to this issue,
you can temporarly use resolution to install this package like this.
and run install again

```
  "resolutions": {
    "@npmcli/package-json":"npm/package-json#v3.0.0"
  },
```

**Comment by Fonger** [comment]
It's coming back now
