### ISSUE TITLE
[BUG] Redirect Installation of package x when a request for package y installation is made using config in package.json

### ISSUE THREAD

**Issue by ganeshkbhat** [npm/package-json#9]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Need to change the entire sourcecode for the npmjs project or use an local alias to install a different package B instead of package A. 

### Expected Behavior

I should be able to redirect installation of a `npmjs A` package to `npmjs B` package from `package.json` `config`.

Citing my repositories as an example to ensure not to make [phpcgijs](https://www.npmjs.com/package/phpcgijs) old versions unfindable. What I am wishing to do is redirect [phpcgijs](https://www.npmjs.com/package/phpcgijs) to [cgijs](https://www.npmjs.com/package/cgijs)

`package.json`
```
{
...
"repository": {
    "type": "git",
    "url": "https://github.com/ganeshkbhat/cgi-js.git",
    "redirect": "newpackagename_preferably--OR--differentrepository"
  }
}
```

OR

```
{
...
"redirect": "newpackagename_preferably"
"repository": {
    "type": "git",
    "url": "https://github.com/ganeshkbhat/cgi-js.git"
  }
}
```

### Steps To Reproduce

NA

### Environment

- npm: Current
- Node: Current
- OS: Windows / Linux / Mac
- platform: Windows / Linux / Mac

**Comment by ganeshkbhat** [comment]
Merging Issues. Seems this feature is being worked on already. I was not aware or communicated. I though that was not nice at all.

https://github.com/npm/cli/issues/5009
https://github.com/npm/config/issues/76
https://github.com/npm/package-json/issues/9

**Comment by ganeshkbhat** [comment]
Citing npm package being pushed in as spam based on these articles I wish to push this as a reason to avoid false positives for a few percent of npm packages which were published as new packages:

- https://blog.sandworm.dev/one-in-two-new-npm-packages-is-seo-spam-right-now , and 
- https://developers.slashdot.org/story/23/03/30/184239/one-in-two-new-npm-packages-is-seo-spam-right-now 

While there may be a lot of spam packages, if you have duplicate package - renamed or republished due to some reason allowing redirect of a npm package to a different package name is definitely going to be a critical feature. You may want to do two this as per my view here:

1) `npm package one` -> redirect -> `npm package two` using keyword in `package.json` (the feature will install `npm package two` instead of `npm package one`).
2) `npm package one` -> redirect -> `npm package two` when opening the npm website (or alternatively put a note in npmjs  website that the `npm package one` is deprecated in favour of `npm package two` and that installation of `npm package one` will lead to installation of `npm package two`).

I am now updating the expected behaviour in the issues from: 

`I should be able to redirect a npmjs A package to npmjs B package from package.json config.` to `I should be able to redirect installation of a npmjs A package to npmjs B package from package.json config.`

**Comment by ganeshkbhat** [comment]
https://github.com/npm/cli/issues/5009

**Comment by wraithgar** [comment]
[overrides](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides) are what you're looking for.
